
// IMMEDIATELY INVOKED FUNCTIONS EXPRESSIONS (IIFE)

//--anotherway of doing function just put sq bracket in function and dont call function 
//--inspite give one sq brackets in place of function call...

//**** It is called IIFE which is used to execute  function immediately but mainly BCZ there can be some 
// plroblem bcz of global pollution so to remove global scope pollution we use IIFE
(function code(){
    console.log("batabase");
    
})();